<?php
// Suppress warnings for PDF generation
error_reporting(E_ERROR | E_PARSE);
ini_set('display_errors', 0);

require_once __DIR__ . '/../helpers.php';
require_once __DIR__ . '/../classes/Database.php';
require_once __DIR__ . '/../vendor/tcpdf/tcpdf.php';

if (!is_admin()) {
    header('Location: ../index.php');
    exit;
}

$db = new Database();
$pdo = $db->getPdo();

// Query data
$query = "
    SELECT bh.borrow_date, bh.due_date,
           CONCAT(u.first_name, ' ', COALESCE(u.middle_name, ''), ' ', u.last_name) as borrower_name,
           b.title, b.author
    FROM borrow_history bh
    JOIN users u ON bh.user_id = u.id
    JOIN books b ON bh.book_id = b.id
    WHERE bh.status = 'borrowed'
    ORDER BY bh.borrow_date DESC
";
$stmt = $pdo->prepare($query);
$stmt->execute();
$data = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Create PDF
$pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);
$pdf->SetCreator('Library System');
$pdf->SetAuthor('Admin');
$pdf->SetTitle('Borrowed Books Report');
$pdf->SetSubject('Borrowed Books Report');

// Set margins
$pdf->SetMargins(15, 25, 15);
$pdf->SetHeaderMargin(5);
$pdf->SetFooterMargin(10);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, 15);

// Add a page
$pdf->AddPage();

// Header
// $pdf->Image(__DIR__ . '/../image/wmsulogo.png', 15, 10, 20, 20, 'PNG');
$pdf->SetFont('helvetica', 'B', 16);
$pdf->Cell(0, 10, 'Western Mindanao State University', 0, 1, 'C');
$pdf->SetFont('helvetica', 'B', 14);
$pdf->Cell(0, 8, 'Library Book Borrowing System', 0, 1, 'C');
$pdf->Ln(5);

// Report title
$pdf->SetFont('helvetica', 'B', 12);
$pdf->Cell(0, 8, 'Borrowed Books Report', 0, 1, 'C');
$pdf->Ln(5);

// User and date info
$pdf->SetFont('helvetica', '', 10);
$pdf->Cell(0, 6, 'Generated by: Admin (' . htmlspecialchars($_SESSION['user']['full_name']) . ')', 0, 1);
$pdf->Cell(0, 6, 'Date & Time: ' . date('F j, Y, g:i A'), 0, 1);
$pdf->Ln(5);

// Table header
$pdf->SetFont('helvetica', 'B', 9);
$pdf->SetFillColor(128, 0, 0);
$pdf->SetTextColor(255);
$pdf->Cell(40, 8, 'Book Title', 1, 0, 'C', 1);
$pdf->Cell(30, 8, 'Author', 1, 0, 'C', 1);
$pdf->Cell(40, 8, 'Borrower Name', 1, 0, 'C', 1);
$pdf->Cell(30, 8, 'Date Borrowed', 1, 0, 'C', 1);
$pdf->Cell(30, 8, 'Due Date', 1, 1, 'C', 1);

// Table data
$pdf->SetFont('helvetica', '', 8);
$pdf->SetTextColor(0);
$fill = false;
foreach ($data as $row) {
    $pdf->SetFillColor(245, 245, 245);
    $pdf->Cell(40, 6, htmlspecialchars(substr($row['title'], 0, 25)), 1, 0, 'L', $fill);
    $pdf->Cell(30, 6, htmlspecialchars(substr($row['author'], 0, 20)), 1, 0, 'L', $fill);
    $pdf->Cell(40, 6, htmlspecialchars(substr($row['borrower_name'], 0, 25)), 1, 0, 'L', $fill);
    $pdf->Cell(30, 6, $row['borrow_date'] ? date('M d, Y', strtotime($row['borrow_date'])) : '-', 1, 0, 'C', $fill);
    $pdf->Cell(30, 6, $row['due_date'] ? date('M d, Y', strtotime($row['due_date'])) : '-', 1, 1, 'C', $fill);
    $fill = !$fill;
}

// Footer
$pdf->SetY(-15);
$pdf->SetFont('helvetica', 'I', 8);
$pdf->Cell(0, 10, 'Generated by Library Book Borrowing System', 0, 0, 'C');

// Output PDF
$pdf->Output('borrowed_books_report.pdf', 'D');
exit;
