<?php
// Suppress warnings for PDF generation
error_reporting(E_ERROR | E_PARSE);
ini_set('display_errors', 0);

require_once __DIR__ . '/../helpers.php';
require_once __DIR__ . '/../classes/Database.php';
require_once __DIR__ . '/../vendor/tcpdf/tcpdf.php';

if (!is_admin()) {
    header('Location: ../index.php');
    exit;
}

$db = new Database();
$pdo = $db->getPdo();

// Query data
$query = "
    SELECT u.username, u.role, CONCAT(u.first_name, ' ', COALESCE(u.middle_name, ''), ' ', u.last_name) as full_name,
           COUNT(bh.id) as total_books_borrowed,
           CASE WHEN u.penalty_status = 'blocked' THEN 'Blocked' ELSE 'Active' END as account_status
    FROM users u
    LEFT JOIN borrow_history bh ON u.id = bh.user_id
    WHERE u.role = 'student'
    GROUP BY u.id, u.username, u.role, u.first_name, u.middle_name, u.last_name, u.penalty_status
    ORDER BY total_books_borrowed DESC
";
$stmt = $pdo->prepare($query);
$stmt->execute();
$data = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Create PDF
$pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);
$pdf->SetCreator('Library System');
$pdf->SetAuthor('Admin');
$pdf->SetTitle('User Activity Report');
$pdf->SetSubject('User Activity Report');

// Set margins
$pdf->SetMargins(15, 25, 15);
$pdf->SetHeaderMargin(5);
$pdf->SetFooterMargin(10);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, 15);

// Add a page
$pdf->AddPage();

// Header
// $pdf->Image(__DIR__ . '/../image/wmsulogo.png', 15, 10, 20, 20, 'PNG');
$pdf->SetFont('helvetica', 'B', 16);
$pdf->Cell(0, 10, 'Western Mindanao State University', 0, 1, 'C');
$pdf->SetFont('helvetica', 'B', 14);
$pdf->Cell(0, 8, 'Library Book Borrowing System', 0, 1, 'C');
$pdf->Ln(5);

// Report title
$pdf->SetFont('helvetica', 'B', 12);
$pdf->Cell(0, 8, 'User Activity Report', 0, 1, 'C');
$pdf->Ln(5);

// User and date info
$pdf->SetFont('helvetica', '', 10);
$pdf->Cell(0, 6, 'Generated by: Admin (' . htmlspecialchars($_SESSION['user']['full_name']) . ')', 0, 1);
$pdf->Cell(0, 6, 'Date & Time: ' . date('F j, Y, g:i A'), 0, 1);
$pdf->Ln(5);

// Table header
$pdf->SetFont('helvetica', 'B', 9);
$pdf->SetFillColor(128, 0, 0);
$pdf->SetTextColor(255);
$pdf->Cell(30, 8, 'Username', 1, 0, 'C', 1);
$pdf->Cell(20, 8, 'Role', 1, 0, 'C', 1);
$pdf->Cell(40, 8, 'Total Books Borrowed', 1, 0, 'C', 1);
$pdf->Cell(30, 8, 'Account Status', 1, 1, 'C', 1);

// Table data
$pdf->SetFont('helvetica', '', 8);
$pdf->SetTextColor(0);
$fill = false;
foreach ($data as $row) {
    $pdf->SetFillColor(245, 245, 245);
    $pdf->Cell(30, 6, htmlspecialchars($row['username']), 1, 0, 'L', $fill);
    $pdf->Cell(20, 6, ucfirst($row['role']), 1, 0, 'C', $fill);
    $pdf->Cell(40, 6, $row['total_books_borrowed'], 1, 0, 'C', $fill);
    $pdf->Cell(30, 6, $row['account_status'], 1, 1, 'C', $fill);
    $fill = !$fill;
}

// Footer
$pdf->SetY(-15);
$pdf->SetFont('helvetica', 'I', 8);
$pdf->Cell(0, 10, 'Generated by Library Book Borrowing System', 0, 0, 'C');

// Output PDF
$pdf->Output('user_activity_report.pdf', 'D');
exit;
